[package]
name = "script"
version = "0.3.0"
edition = "2021"
license = "MIT"
repository = "https://lab.themackabu.dev/self/script"
description = "barebones http scripting"

[dependencies]
actix-web = "4.5.1"
anyhow = "1.0.80"
askama = "0.12.1"
colored = "2.1.0"
home = "0.5.9"
lazy_static = "1.4.0"
macros-rs = "1.2.1"
mime = "0.3.17"
peg = "0.8.2"
redis = "0.24.0"
rhai-fs = "0.1.3"
rhai-url = "0.0.5"
serde_json = "1.0.114"
smartstring = "1.0.1"
termcolor = "1.4.1"
tokio = "1.36.0"
toml = "0.8.10"
tracing = "0.1.40"
tracing-bunyan-formatter = "0.3.9"
tracing-subscriber = "0.3.18"

[mongodb]
default-features = false
features = ["sync"]
version = "2.8.1"

[pickledb]
features = [
	 "json",
	 "bincode",
	 "cbor",
	 "yaml",
]
version = "0.5.1"

[regex]
package = "fancy-regex"
version = "0.12.0"

[reqwest]
features = ["blocking"]
version = "0.11.24"

[rhai]
features = [
	 "serde_json",
	 "serde",
]
version = "1.17.1"

[serde]
features = ["derive"]
version = "1.0.197"
