[package]
name = "httpin"
version = "0.1.0"
edition = "2021"

[dependencies]
rhai-fs = "0.1.3"
rhai-url = "0.0.5"
actix-web = "4.4.0"
macros-rs = "0.5.0"
termcolor = "1.4.0"
once_cell = "1.19.0"
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
rhai = { version = "1.16.3", features = ["serde_json", "serde"] }
regex = "1.10.2"
