[package]
name = "script"
version = "0.3.1"
edition = "2021"
license = "MIT"
repository = "https://lab.themackabu.dev/self/script"
description = "barebones http scripting"

[profile.release]
strip = true

[dependencies]
peg = "0.8.4"
home = "0.5.9"
mime = "0.3.17"
toml = "0.8.19"
redis = "0.24.0"
tokio = "1.40.0"
anyhow = "1.0.86"
askama = "0.12.1"
colored = "2.1.0"
rhai-fs = "0.1.3"
rhai-url = "0.0.5"
tracing = "0.1.40"
actix-web = "4.9.0"
macros-rs = "1.2.5"
termcolor = "1.4.1"
smartstring = "1.0.1"
serde_json = "1.0.127"
tracing-subscriber = "0.3.18"
tracing-bunyan-formatter = "0.3.9"

[dependencies.mongodb]
default-features = false
features = ["sync"]
version = "2.8.2"

[dependencies.pickledb]
features = [
	 "json",
	 "bincode",
	 "cbor",
	 "yaml",
]
version = "0.5.1"

[dependencies.regex]
package = "fancy-regex"
version = "0.12.0"

[dependencies.reqwest]
features = ["blocking"]
version = "0.11.27"

[dependencies.rhai]
features = [
	 "serde_json",
	 "serde",
]
version = "1.19.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.209"
