[package]
name = "httpin"
version = "0.1.0"
edition = "2021"

[dependencies]
peg = "0.8.2"
rhai-fs = "0.1.3"
rhai-url = "0.0.5"
actix-web = "4.4.0"
macros-rs = "0.5.0"
termcolor = "1.4.0"
lazy_static = "1.4.0"
serde_json = "1.0.108"
fancy-regex = "0.12.0"
serde = { version = "1.0.193", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["blocking"] }
rhai = { version = "1.16.3", features = ["serde_json", "serde"] }