[package]
name = "httpin"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
axum = "0.7.2"
lazy_static = "1.4.0"
once_cell = "1.19.0"
rhai = { version = "1.16.3", features = ["serde_json"] }
rocket = { version = "0.5.0", features = ["json"] }
rune = "0.13.1"
tokio = { version = "1.34.0", features = ["full"] }
