[project]
name = "script"
version = "0.2.3"

[tasks]
clean = { script = ["rm -rf bin", "mkdir bin"] }
run = { script = ["maid build -q", "bash -c './bin/script | bunyan'"] }

[tasks.build]
depends = ["clean"]
script = [
   "cargo zigbuild --release", 
   "cp target/release/script bin/script"
]

[tasks.build.cache]
path = "src"
target = ["bin/script"]